spring:
    data:
        cassandra:
            port: 9042
            local-datacenter: datacenter1
            contact-points: localhost
            keyspace-name: juicyfruit
server:
    port: 3006